---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
implicit:
  - Пользователь должен иметь возможность зарегистрироваться и авторизоваться на сайте
  - Пользователь должен иметь возможность перемещаться по всей навигации сайта
  - Пользователь должен иметь возможность просматривать товары, которые "есть" и "нет" в наличии
  - Пользователь должен иметь возможность регулировать цену товара "от" и "до" для фильтрации
  - На странице товара и в каталоге пользователь должен иметь возможность видеть рейтинг и цену каждого товара со скидкой и "без"
  - Пользователь должен иметь возможность удалять товары из корзины
  - Пользователь должен иметь возможность видеть общую сумму товаров в корзине
  - Пользователь должен иметь возможность оформить заказ
  - Сайт должен быть адаптирован для разных видов устройств
  - У сайта должно быть две версии языка, русский и английский
  - Сайт должен быть локализован на разных версиях языка
