---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Сайт должен быть доступен на различных устройствах
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
implicit:
  - Пользователь должен иметь возможность зарегистрироваться и авторизоваться на сайте, чтобы оставить данные для обратной связи
  - Пользователь должен иметь возможность на аутентификацию
  - Пользователь должен иметь возможность перемещаться по всей навигации сайта
  - Пользователь должен иметь возможность просматривать историю заказов в личном кабинете
  - На главной странице под колонкой фильтров должна быть кнопка сброса всех фильтров
  - Возможность просматривать товары, которые "есть" в наличии
  - Возможность регулировать цену товара "от" и "до" для поиска
  - Возможность сортировки товара по цене "от меньшей к большей" и от "большей к меньшей"
  - Возможность сортировки товара по количеству покупок
  - Пользователь должен иметь возможность удалять товары из корзины и полностью очищать корзину 
  - Добавив товар в корзину, на этой же странице пользователь может сразу перейти к оформлению
  - Пользователь должен иметь возможность видеть общую сумму товаров в корзине
  - Пользователь должен иметь возможность оформить заказ
  - Сайт должен поддерживать английский язык
  - Сайт должен быть адаптирован для разных видов устройств
  - Сайт должен быть локализован на разных версиях языка


