---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Сайт должен быть доступен на различных устройствах
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
implicit:
  - Пользователь должен иметь возможность перемещаться по всей навигации сайта. Переходить из каталога в корзину и обратно 
  - Добавленные товары корзины должны хранится в сессии браузера
  - Проверка выбора фильтрации по категории "Все товары" 
  - На главной странице под колонкой фильтров должна быть кнопка сброса всех фильтров
  - Возможность просматривать товары, которые "есть" в наличии
  - Возможность регулировать цену товара "от" и "до" для поиска
  - Пользователь должен иметь возможность перемещаться по всем страницам каталога
  - Пользователь должен иметь возможность редактировать количество товара корзины
  - Пользователь должен иметь возможность удалять товары из корзины и полностью очищать корзину 
  - Пользователь должен иметь возможность видеть общую сумму товаров в корзине
  - Пользователь должен иметь возможность оформить заказ
  - Сайт должен поддерживать английский язык
  - Сайт должен быть адаптирован для разных видов устройств


